/*****************************************************************
 * 
 *     !!! DON'T MODIFY THIS FILE !!! 
 * 
 *      THIS HEADER WAS GENERATED BY 
 *      OCTOPUS BOX BUILDER 
 *      VERSION 311
 *
 *****************************************************************/
#ifndef _DS_BOXXPLANE_
#define _DS_BOXXPLANE_

#include "ds_error.h"
#include "ds_interface.h"
#include "stdio.h"

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  /* Xplane altitude over ground level [m] */
  float agl_xplane;
  float ground_elev_xplane;
} BoxXplane_T;
/****************************************************************
 * ZUWEISUNG:
 *
 *               "boxname"     <->     BoxXplane_T
 *
 * FUNKTIONSAUFRUF:
 *
 *        ds_initialize_BoxXplane(char *boxname  , char *s1);
 *
 * DATENSTRUKTUR im DATENPOOL:
 *
 *      "boxname"----|
 *                   |-----------"s1".SUR.COLL.agl_xplane
 *                   |-----------"s1".SUR.COLL.ground_elev_xplane
 * 
 *               "s1": ACR#(1-2)
 * 
 * 
 *****************************************************************/ 
ds_error ds_initialize_BoxXplane(char *boxname  , char *s1);

#ifdef __cplusplus 
} 
#endif

#endif

