/*****************************************************************
 * 
 *     !!! DON'T MODIFY THIS FILE !!! 
 * 
 *      THIS HEADER WAS GENERATED BY 
 *      OCTOPUS BOX BUILDER 
 *      VERSION 311
 *
 *****************************************************************/
#include "ds_BoxXplane.h"

/****************************************************************
 * ZUWEISUNG:
 *
 *               "boxname"     <->     BoxXplane_T
 *
 * FUNKTIONSAUFRUF:
 *
 *        ds_initialize_BoxXplane(char *boxname  , char *s1);
 *
 * DATENSTRUKTUR im DATENPOOL:
 *
 *      "boxname"----|
 *                   |-----------"s1".SUR.COLL.agl_xplane
 *                   |-----------"s1".SUR.COLL.ground_elev_xplane
 * 
 *               "s1": ACR#(1-2)
 * 
 * 
 *****************************************************************/ 


ds_error ds_initialize_BoxXplane(char *boxname  , char *s1){

  BoxXplane_T tempstruct;

  char string1 [255];
  char string2 [255];

  sprintf(string1,"%s.SUR.COLL.agl_xplane" ,s1);
  ds_new_alias(string1,"float","0",(char*)  0,(char*)  0,(char*)  0);

  sprintf(string2,"%s.SUR.COLL.ground_elev_xplane" ,s1);
  ds_new_alias(string2,"float","0",(char*)  0,(char*)  0,(char*)  0);

  ds_create_box (boxname, sizeof(BoxXplane_T) , (char *)&tempstruct, 
                 string1,            (char *)&tempstruct.agl_xplane,
                 string2,            (char *)&tempstruct.ground_elev_xplane,
                 (char *) 0);
  return DS_EOK;
}
